version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8081:8080"  # Expose Keycloak on port 8081
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #DB_VENDOR: H2  # You can change this to your preferred database, like PostgreSQL or MySQL
    depends_on:
      - mongo
    volumes:
      - ./keycloak/config:/opt/jboss/keycloak/standalone/configuration  # Mount local configuration folder
      - ./lab-realm.json:/opt/keycloak/data/import/lab-realm.json
    #command: start-dev
    command: ["start-dev", "--import-realm"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch-ll
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana-ll
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    container_name: redis-ll
    ports:
      - "6379:6379"

volumes:
  mongo-data:
  keycloak:
  esdata:
    driver: local